// Repository scaffolding for Workbench layout.
// Invariants: uses default config paths; never overwrites unless force is true.
namespace Workbench.Core;

public static class ScaffoldService
{
    /// <summary>
    /// Result payload returned by scaffold operations.
    /// </summary>
    /// <param name="Created">Paths created during scaffolding.</param>
    /// <param name="Skipped">Paths skipped because they already existed.</param>
    /// <param name="ConfigPath">Path to the config file.</param>
    public sealed record ScaffoldResult(IList<string> Created, IList<string> Skipped, string ConfigPath);

    public static ScaffoldResult Scaffold(string repoRoot, bool force)
    {
        var config = WorkbenchConfig.Default;
        var created = new List<string>();
        var skipped = new List<string>();

        void EnsureDir(string relativePath)
        {
            var path = Path.Combine(repoRoot, relativePath);
            Directory.CreateDirectory(path);
        }

        void WriteFile(string relativePath, string content)
        {
            var path = Path.Combine(repoRoot, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? repoRoot);
            if (File.Exists(path) && !force)
            {
                skipped.Add(relativePath);
                return;
            }
            File.WriteAllText(path, content);
            created.Add(relativePath);
        }

        EnsureDir(config.Paths.DocsRoot);
        EnsureDir(config.Paths.SpecsRoot);
        EnsureDir(config.Paths.ArchitectureDir);
        EnsureDir("contracts");
        EnsureDir("decisions");
        EnsureDir("runbooks");
        EnsureDir("tracking");
        EnsureDir("templates");
        EnsureDir("schemas");

        EnsureDir(config.Paths.WorkRoot);
        EnsureDir(config.Paths.ItemsDir);
        EnsureDir(config.Paths.DoneDir);
        EnsureDir(config.Paths.TemplatesDir);

        WriteFile(Path.Combine(config.Paths.DocsRoot, "README.md"), BuildOverviewReadmeTemplate());
        WriteFile(Path.Combine("contracts", "README.md"), BuildContractsReadmeTemplate());
        WriteFile(Path.Combine("decisions", "README.md"), BuildDecisionsReadmeTemplate());
        WriteFile(Path.Combine("runbooks", "README.md"), BuildRunbooksReadmeTemplate());
        WriteFile(Path.Combine("tracking", "README.md"), BuildTrackingReadmeTemplate());
        WriteFile(Path.Combine("templates", "README.md"), BuildDocTemplatesReadmeTemplate());

        WriteFile(Path.Combine(config.Paths.SpecsRoot, "README.md"), BuildSpecsReadmeTemplate());
        WriteFile(Path.Combine(config.Paths.ArchitectureDir, "README.md"),
            "# Architecture\n\nArchitecture and design documents live here under domain folders.\n");

        var workReadmePath = Path.Combine(config.Paths.WorkRoot, "README.md");
        WriteFile(workReadmePath,
            """
            ---
            workbench:
              type: doc
              workItems: []
              codeRefs: []
            owner: platform
            status: active
            updated: 0000-00-00
            ---

            # Work

            Work items and the day-to-day board for delivery.

            ## Workboard

            Generated by `workbench nav sync --workboard`.

            <!-- workbench:workboard:start -->
            ## Now (in-progress)

            _None._

            ## Next (ready)

            _None._

            ## Blocked

            _None._

            <details>
            <summary>Draft (backlog) (0)</summary>

            _None._

            </details>
            <!-- workbench:workboard:end -->

            ## Layout

            - `overview`: high-level product, standard, and orientation docs.
            - `contracts`: CLI, API, and schema contracts.
            - `decisions`: ADRs and tradeoff history.
            - `runbooks`: operational procedures and playbooks.
            - `tracking`: milestone and delivery notes.
            - `templates`: reusable document templates.
            - `schemas`: JSON Schemas for repo contracts.
            - `work/items`: active work items named `<ID>-<slug>.md`.
            - `work/done`: closed items for reference and audit history.
            - `work/templates`: templates used to create new work items.
            - `specs`: canonical specification documents.
            - `architecture`: architecture and design documents.

            ## Source of truth

            - Hand-author the individual work item files under `work/items` for canonical items.
            - Treat the workboard and index sections between `workbench:` markers as generated views maintained by `workbench nav sync` or `workbench board regen`.
            - Keep the `work` tree for work items and generated workboard views.

            ## Workflow

            1. Create a work item with `workbench item new`, `workbench item generate`, or `workbench voice workitem`.
            2. Edit the Markdown file to tighten the summary, context, traceability, implementation notes, acceptance criteria, and notes.
            3. Link specs, architecture docs, ADRs, files, PRs, or issues with `workbench item link`, and use `workbench promote` when you want branch + commit scaffolding.
            4. Refresh the generated views with `workbench nav sync` and run `workbench validate` before review or automation.

            ## Index

            Generated by `workbench nav sync`.

            <!-- workbench:work-index:start -->
            <!-- workbench:work-index:end -->
            """);
        if (!string.Equals(config.Paths.WorkboardFile, workReadmePath, StringComparison.OrdinalIgnoreCase))
        {
            WriteFile(config.Paths.WorkboardFile,
                "# Workboard\n\n## Now (in-progress)\n\n_None._\n\n## Next (ready)\n\n_None._\n\n## Blocked\n\n_None._\n\n## Draft\n\n_None._\n");
        }
        WriteFile(Path.Combine(config.Paths.ItemsDir, "README.md"),
            "# Items\n\nActive work items live here as Markdown files named `<ID>-<slug>.md`.\n");
        WriteFile(Path.Combine(config.Paths.DoneDir, "README.md"),
            "# Done\n\nCompleted work items may be moved here when closed.\n");
        WriteFile(Path.Combine(config.Paths.TemplatesDir, "README.md"),
            "# Work Item Templates\n\nWork item templates used by `workbench item new`.\n");

        WriteFile(Path.Combine(config.Paths.TemplatesDir, "work-item.bug.md"), DefaultBugTemplate);
        WriteFile(Path.Combine(config.Paths.TemplatesDir, "work-item.task.md"), DefaultTaskTemplate);
        WriteFile(Path.Combine(config.Paths.TemplatesDir, "work-item.spike.md"), DefaultSpikeTemplate);

        var configPath = WorkbenchConfig.GetConfigPath(repoRoot);
        var configJson = JsonSerializer.Serialize(config, Workbench.Core.WorkbenchJsonContext.Default.WorkbenchConfig);
        WriteFile(Path.Combine(".workbench", "config.json"), configJson + "\n");

        return new ScaffoldResult(created, skipped, configPath);
    }

    private const string DefaultBugTemplate = """
        ---
        id: BUG-0000
        type: bug
        status: draft
        priority: medium
        owner: null
        created: 0000-00-00
        updated: null
        tags: []
        related:
          specs: []
          adrs: []
          files: []
          prs: []
          issues: []
          branches: []
        ---

        # BUG-0000 - <title>

        ## Summary

        ## Context

        ## Trace Links

        Addresses:

        - REQ-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        Uses Design:

        - ARC-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        Verified By:

        - VER-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        ## Implementation notes
        - Steps to reproduce:
        - Expected behavior:
        - Actual behavior:

        ## Acceptance criteria
        -

        ## Notes
        -
        """;

    private const string DefaultTaskTemplate = """
        ---
        id: TASK-0000
        type: task
        status: draft
        priority: medium
        owner: null
        created: 0000-00-00
        updated: null
        tags: []
        related:
          specs: []
          adrs: []
          files: []
          prs: []
          issues: []
          branches: []
        ---

        # TASK-0000 - <title>

        ## Summary

        ## Context

        ## Trace Links

        Addresses:

        - REQ-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        Uses Design:

        - ARC-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        Verified By:

        - VER-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        ## Implementation notes
        -

        ## Acceptance criteria
        -

        ## Notes
        -
        """;

    private const string DefaultSpikeTemplate = """
        ---
        id: SPIKE-0000
        type: spike
        status: draft
        priority: medium
        owner: null
        created: 0000-00-00
        updated: null
        tags: []
        related:
          specs: []
          adrs: []
          files: []
          prs: []
          issues: []
          branches: []
        ---

        # SPIKE-0000 - <title>

        ## Summary

        ## Context

        ## Trace Links

        Addresses:

        - REQ-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        Uses Design:

        - ARC-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        Verified By:

        - VER-<DOMAIN>[-<GROUPING>...]-<SEQUENCE:4+>

        ## Implementation notes
        - Research notes:

        ## Acceptance criteria
        -

        ## Notes
        -
        """;

    private static string BuildOverviewReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Overview",
            string.Empty,
            "High-level orientation, product summaries, and repo-level standards.",
            string.Empty,
            "## Start here",
            string.Empty,
            "- `specification-and-traceability-standard.md`",
            "- `documentation-structure.md`",
            "- `workbench-spec.md`",
            string.Empty);
    }

    private static string BuildContractsReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Contracts",
            string.Empty,
            "APIs, CLI interfaces, schemas, and external contracts.",
            string.Empty,
            "## Include",
            string.Empty,
            "- `contracts/cli-help.md`",
            "- `contracts/commands.md`",
            "- `contracts/error-codes.md`",
            "- `contracts/test-matrix.md`",
            "- `contracts/test-gate.contract.yaml`",
            "- `schemas/*.json`",
            string.Empty);
    }

    private static string BuildDecisionsReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Decisions",
            string.Empty,
            "Architecture Decision Records (ADRs) and tradeoff history.",
            string.Empty,
            "## Include",
            string.Empty,
            "- `ADR-*.md`",
            "- `templates/adr.md`",
            string.Empty);
    }

    private static string BuildRunbooksReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Runbooks",
            string.Empty,
            "Operational procedures, troubleshooting, and release playbooks.",
            string.Empty,
            "## Include",
            string.Empty,
            "- `runbooks/*.md`",
            "- `templates/runbook.md`",
            string.Empty);
    }

    private static string BuildTrackingReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Tracking",
            string.Empty,
            "Milestones, progress tracking, and delivery notes.",
            string.Empty,
            "## Include",
            string.Empty,
            "- Milestone summaries and delivery notes.",
            "- Status updates or weekly rollups.",
            "- Links back to work items and decisions.",
            string.Empty);
    }

    private static string BuildDocTemplatesReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Document Templates",
            string.Empty,
            "Reusable templates for canonical spec-trace artifacts and related repository docs.",
            string.Empty,
            "## Available templates",
            string.Empty,
            "- `requirement-spec.md`",
            "- `feature-spec.md`",
            "- `architecture.md`",
            "- `verification.md`",
            "- `adr.md`",
            "- `runbook.md`",
            "- `contract.md`",
            string.Empty);
    }

    private static string BuildSpecsReadmeTemplate()
    {
        return string.Join(
            "\n",
            "# Specs",
            string.Empty,
            "Canonical specifications live here. Keep them directly under `specs/` and use the sibling top-level `architecture/` and `work/` roots for design and execution artifacts.",
            string.Empty,
            "## Layout",
            string.Empty,
            "- `specs`: specification documents.",
            "- `architecture`: architecture and design documents grouped by domain.",
            "- `work`: work items, backlog, and workboard files.",
            "- `overview`: high-level product and orientation docs.",
            "- `contracts`: CLI, API, and schema contracts.",
            "- `decisions`: ADRs and tradeoff history.",
            "- `runbooks`: operational procedures and playbooks.",
            "- `tracking`: milestone and delivery notes.",
            string.Empty,
            "## Workflow",
            string.Empty,
            "1. Author or update canonical artifacts in the appropriate family directory.",
            "2. Keep trace links in front matter and body sections aligned with the canonical schema.",
            "3. Run `workbench validate` and `workbench nav sync` after changes.",
            string.Empty);
    }
}
