name: Daily Workbench Sync (Generate Mode)

on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: workbench-daily-sync
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install Workbench CLI tool
        env:
          WORKBENCH_VERSION: 0.1.0
        run: |
          dotnet tool install --global Incursa.Workbench --version "$WORKBENCH_VERSION"
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Sync workbench metadata
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKBENCH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          workbench config set --path github.provider --value octokit
          workbench sync --docs --nav --include-done --force --workboard true

      - name: Validate repo
        run: |
          workbench item normalize --include-done
          workbench validate --strict \
            --skip-doc-schema \
            --link-exclude docs/tabler \
            --link-exclude _reference \
            --link-exclude src/app/Incursa.Platform/Help/Content

      - name: Create pull request for sync updates
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: daily workbench sync"
          title: "chore: daily workbench sync"
          body: "Automated daily sync from Workbench CLI."
          branch: "automation/workbench-daily-sync"
          delete-branch: true
