name: Configure Incursa NuGet credentials
description: "Expose private Incursa feed credentials for dotnet/NuGet commands."
inputs:
  url:
    description: "Private feed URL."
    required: false
    default: "https://nuget.incursa.com/index.json"
  username:
    description: "Username for the private feed."
    required: true
  api-key:
    description: "API key/password for the private feed."
    required: true
runs:
  using: composite
  steps:
    - name: Validate and export NuGet credentials
      shell: bash
      run: |
        set -euo pipefail

        if [ -z "${{ inputs.username }}" ] || [ -z "${{ inputs.api-key }}" ]; then
          echo "Missing required Incursa NuGet credentials (vars: NUGET_INCURSA_USERNAME; secret: NUGET_INCURSA_APIKEY)."
          exit 1
        fi

        {
          echo "NUGET_INCURSA_URL=${{ inputs.url }}"
          echo "NuGetPackageSourceCredentials_incursa=Username=${{ inputs.username }};Password=${{ inputs.api-key }}"
        } >> "$GITHUB_ENV"
